### ISSUE TITLE
Add Python debugger

### ISSUE THREAD

**Issue by windowsboy111** [atom-ide-community/ide-python#204]
Hello there. I want to have a python debugger for atom, so I tried out this package today. 
![image](https://user-images.githubusercontent.com/48051237/87110008-9fcc3800-c298-11ea-9dd4-a3fbbf21d34c.png)
After I install, I go to the debugger panel and I pressed the ![image](https://user-images.githubusercontent.com/48051237/87110086-c8ecc880-c298-11ea-86c5-2ca98501cad8.png) button. And it tells me that 
![image](https://user-images.githubusercontent.com/48051237/87110235-19642600-c299-11ea-96ea-db7c22161918.png)
. I heard that I have to install `atom-ide-debugger-python` with this package (I've forgotten where I've seen this thing)   
But every single time I launch debugger, I will get this message:  
`zipimport.ZipImportError, not a Zip file`
I think this is not really the problem of this package, I think this error indicates that the debugger is `atom-ide-debugger-python`, not this package. But really, after only installing this package, I still don't get a debugger, which is awkward.  
Okay, things are getting a lot weird. I uninstalled `ide-python`, and leave `atom-ide-debugger-python` alone, and now I don't see a single debugger avaliable! I need both!  
Later, I found out that when the zip error pops out I can press the continue (aka the run) button and it runs fine!
![image](https://user-images.githubusercontent.com/48051237/87109934-757a7a80-c298-11ea-87bb-0269677a6918.png)

Which indicates that one of them tries to load an unnecessary zip file which causes an exception.  
I posted this on this repository just because `atom-ide-debugger-python` is archived.  
Hope ppl can help. (Welp I think this is my issue more than the issue of the package, now I think about it...)

**Comment by aminya** [comment]
This will be added soon. It is in my TODO list.

**Comment by aminya** [comment]
The latest release adds a debugger. It also allows running the scripts. It is still experimental. Follow the instructions here:
https://github.com/atom-ide-community/ide-python/releases/tag/v1.6.0
