### ISSUE TITLE
Python does not open file properly

### ISSUE THREAD

**Issue by jejsemin** [atom-ide-community/ide-python#214]
When opening up ipynb files all I get is code (as shown below) in objects instead of Python kernel:
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "___\n",
    "\n",
    "___\n",
    "<center><em>Content Copyright by Pierian Data</em></center>"
   ]
  }

I have Python downloaded, all the relevant packages up to date and still not working.

**Comment by aminya** [comment]
ipynb files are not supported by ide-python. Look at https://atom.io/packages/hydrogen and https://atom.io/packages/jupyter-notebook
