### ISSUE TITLE
Joining @atom-ide-community

### ISSUE THREAD

**Issue by aminya** [atom-ide-community/ide-python#215]
Hi @lgeiger. Thanks for this great package!

 We were wondering if would like to join @atom-ide-community with this package. The community can help to maintain and improve the package. For example, I am planning to add a debugger to ide-python.

**Comment by lgeiger** [comment]
Hi @aminya thanks for reaching out.
It's awesome to see that the @atom-ide-community has taken over support of the IDE functionality in Atom, great work!

I haven't had enough time lately to do a proper job at maintaining this package so I'd be really happy to welcome more people. I think @atom-ide-community would be a great new home for `ide-python` 🎉

**Comment by lgeiger** [comment]
From an organisational perspective, can I just transfer ownership of the repo to the organisation or would this break package publishing?

**Comment by aminya** [comment]
> Hi @aminya thanks for reaching out.
It's awesome to see that the @atom-ide-community has taken over support of the IDE functionality in Atom, great work!

You are welcome!

> I haven't had enough time lately to do a proper job at maintaining this package so I'd be really happy to welcome more people. I think @atom-ide-community would be a great new home for ide-python 🎉

This would be awesome! 

> From an organisational perspective, can I just transfer ownership of the repo to the organisation or would this break package publishing?

You can transfer the package to the organization. It does not affect publishing. Everyone will continue to get the updates.

**Comment by aminya** [comment]
Thanks for joining us. 🎉 I am closing this issue.

**Comment by lgeiger** [comment]
Great to be here 🚀
