### ISSUE TITLE
Updating to “ide-python@1.6.2” failed

### ISSUE THREAD

**Issue by aceventura82** [atom-ide-community/ide-python#227]
Hi,

When Atom tries to update to the version 1.6.2 of ide-python I'm getting some npm errors

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! Invalid dependency type requested: alias

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oz/.atom/.apm/_logs/2020-11-17T12_47_01_802Z-debug.log

I'm Using 
Fedora KDE: 33
Atom Beta: 1.41.0-beta1
Python 3.9.0
npm: 6.14.8

Current ide-python: 1.5.2

Here is is the full log: [PastePin Log](https://pastebin.com/8fsEyZPq)

**Comment by dvanderfaeillie** [comment]
I can confirm the same error on Elementary OS running: 
 
    Atom    : 1.47.0
    Electron: 5.0.13
    Chrome  : 73.0.3683.121
    Node    : 12.0.0

**Comment by dvanderfaeillie** [comment]
@aceventura82 My error got fixed when updating to the latest atom (1.53.0)

**Comment by aceventura82** [comment]
Updating atom fix the issue
